version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment: 
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_DB="todo-db"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - postgres
      
  # server:
  #   container_name: server
  #   build: 
  #     context: ./server
  #     dockerfile: Dockerfile
  #   depends_on: 
  #     - postgres
  #   environment:
  #     - DATABASE_URL_WITH_SCHEMA="postgres://postgres:postgres@postgres:5432/todo-db?schema=public"
  #     - DATABASE_URL="postgres://postgres:postgres@postgres:5432/todo-db"
  #     - NODE_ENV="development"
  #     - PORT="3000"
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./server/src:/usr/src/app/src
  #   links:
  #     - postgres